USE WAREHOUSE CUST_WH;
USE DATABASE DE_DB;
put file://D:\SFE\customer_data_3.csv @DE_STAGE auto_compress=true;
USE WAREHOUSE CUST_WH;
USE DATABASE DE_DB;
CREATE or REPLACE file format CUSTFORMAT
  type = 'CSV'
  field_delimiter = ','
  skip_header = 1;
COPY INTO TDW_DW.CUSTOMER (
CUSTOMER_ID, 
GENDER,
AGE,
ANNUAL_INCOME,
SPENDING_SCORE,
INS_TS,
UPD_TS) FROM ( SELECT t.$1 AS CUSTOMER_ID,t.$2 AS GENDER,t.$3 AS AGE,t.$4 AS ANNUAL_INCOME,t.$5 AS SPENDING_SCORE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM  @DE_STAGE/customer_data_3.csv.gz t) FILE_FORMAT = CUSTFORMAT;


